### ISSUE TITLE
Incoming calls working perfectly but cannot schedule Outgoing calls 

### ISSUE THREAD

**Issue by MusinguziMak** [ConnectForLife/cfl-distribution#2]
Hello. I am not certain if this is the right place to ask this. We have built a new application based on the connectforlife distribution and a new module we have built specifically for our needs. We have built new callflows and are able to make incoming calls perfectly. The "initiate call" link/button works perfectly as well. 

We are failing to make/schedule any messages for an outgoing call despite all efforts. There are no error/exception messages being thrown or logged so we cannot easily trace the problem. Is there a known issue with the scheduling of outgoing calls? 

PS. We have not made any changes to the messages module or any other scheduling related module. 

Many thanks

**Comment by pwargulak** [comment]
Hello @MusinguziMak 
did you check the documentation: https://github.com/ConnectForLife/cfl-distribution/wiki/Messages#messages-functionalities---patient 

When you setup a schedule (for example health tip) on a patient's messages page, does future events appear on that patient's messages calendar? Is message service activated - either Call or SMS is selected? 

Generally, once you setup a schedule via messages pages, you should be able to see future events in the calendar. The next step would be to verify if _Messages Deliveries Job Task_ runs and schedules tasks for "message sending" (which is either sending an SMS or making a Call). That "message sending" tasks have job class: ServiceGroupDeliveryJobDefinition and the name looks like: a:XXXp:XXXd:YYYYMMDDHHmmUTC

We'll think about some other tips.

Best regards

**Comment by pwargulak** [comment]
Closing - looks like it's solved.
