### ISSUE TITLE
How can I create API endpoints to pick patient alerts and also insert patient alerts into this distribution 

### ISSUE THREAD

**Issue by hkaluuma** [ConnectForLife/cfl-distribution#3]
Hello, I am trying to create an API endpoint to access alerts raised on patients and another to post patient alerts to the system through the API.

Currently I am trying to use the openmrs-module-webservices.rest module to access the code of the API so that I can try to figure out how to create an endpoint for the alerts.

My challenge is that I don't see where the actual codes of the existing endpoints are and I don't know how I can add a new endpoint into the API and the distribution.

I would really appreciate any assistance, directions or advice you can offer me on this

**Comment by pwargulak** [comment]
Hi @hkaluuma 

I'm not sure what you mean by patient alerts, but regarding REST APIs you have two options:

1. The OpenMRS framework has some generic way of implementing a REST which serves Create-Read-Update-Delete operation on entities. The openmrs-module-webservices.rest contains the implementation of this generic approach for most of the entities. In short, you implement an interface _CrudResource_ and annotate the class with _@Resource_ that configures the OpenMRS to pick-up your implementation when serving REST requests. This might be complex, it has some boilerplate code to make and it is also meant to support different version of an OpenMRS.
See example for Patient (look at parent classes too): https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/PatientResource1_9.java

2. Second option might be simpler. You can implement regular Spring REST controller. The example is in omrs-visits module. You can ignore the swagger annotations, we use that to generate API docs.
See class here: https://github.com/ConnectForLife/openmrs-module-visits/blob/main/omod/src/main/java/org/openmrs/module/visits/web/controller/VisitController.java

Best regards,
PiotrW

**Comment by hkaluuma** [comment]
Thank you for that feedback. I am going to explore the second option first. When I stated patient alerts I meant symptom alerts.
I really appreciated this guidance you have offered.

**Comment by pwargulak** [comment]
Closing - we can reopen if there will be more questions.

**Comment by hkaluuma** [comment]
Hello @pwargulak, how do I access the API docs

**Comment by pwargulak** [comment]
Hi @hkaluuma 

the general OpenMRS REST API documentation is here: https://rest.openmrs.org/#openmrs-rest-api 

For the Connect for Life specific documentation, the currently have only one option which is available when you have access to running server. Go to the Advanced Administration (.../openmrs/admin/index.htm) and in a module's section there are links with names ending with "... Module REST API", it will redirect you to Swagger documentation for our REST API.

Best regards,
PiotrW

**Comment by hkaluuma** [comment]
That has been noted thank you.
