### ISSUE TITLE
Implement rules for a  field  to only display when a user  selects a particular option

### ISSUE THREAD

**Issue by AnnetKabuye** [ConnectForLife/cfl-distribution#4]
Hello team, I  would  like to add rules in  the cflui.registerPatient json script to only display some fields  when a  user  selects a  particular  option. In  my  patient registration form, I  have a  question  about pregnancy and  it  only applies  to  females, so  I  need  a  way of  skipping it  for  male  clients. Please  see  part  of  the  json script  for  details.

https://pastebin.com/DT9DQzc8

Annet

**Comment by pwargulak** [comment]
Hi @AnnetKabuye 

I'm sorry for a late response. 
Currently this kind of conditional input is not supported. Our FE developer @rstencel is looking into possible solutions.

Best regards,
PiotrW

**Comment by rstencel** [comment]
Hi @AnnetKabuye 

As @pwargulak mentioned this functionality is yet to be implemented. I have created a task in our backlog and a member of our team will let you know (here) as soon as we start working on this task.

Best regards,
Rafał

**Comment by ChristofStey** [comment]
Closing as this functionality will not be part of sprints in the near future.  If this changes, I will reopen.
