### ISSUE TITLE
API endpoint to connect with other applications like a mobile app

### ISSUE THREAD

**Issue by Byenkya** [ConnectForLife/cfl-distribution#6]
Hello, 
I just wanted to know whether there is an API end point for making calls in openmrs (based on the Connect for Life Distribution ) that can be used with external applications for example a mobile app or any other web based app like in python i.e where I can just fill in the number of a person within my mobile app, make a post request to the server to initiate the call based on some parameters. Any assistance will be highly appreciated

**Comment by Byenkya** [comment]
Which API entry point should I use to register a patient  from this page of end points (http://localhost:8080/openmrs/module/webservices/rest/apiDocs.htm)  just like some who uses the Admin portal to register.

**Comment by pwargulak** [comment]
Hi @Byenkya 
There is "/patientRegistration" endpoint ../openmrs/ms/uiframework/resource/cfl/swagger/index.html
but it seems that a POST body is wrong there.

The example of POST body JSON:
`
{
  LocationAttribute: "8d6c993e-c2cc-11de-8d13-0010c6dffd0f",
  Nationality: "Belgium",
  Telephone Number: "63123123123",
  Vaccination program: "Vacc1",
  address1: "Address1",
  address2: "Address2",
  birthdate: "2022-07-04",
  birthdateEstimated: false,
  cityVillage: "City",
  country: "Country",
  familyName: "FamilyName",
  gender: "M",
  givenName: "GivenName",
  middleName: "MiddleName",
  personLanguage: "English",
  postalCode: "PostalCode",
  stateProvince: "State"
}
`

For any other Person Attribute, you just add another field to the JSON object, where a field name is a name of Person Attribute and value is an attribute's value string representation.

For example, for String-type Person Attribute "Favorite dish" the JSON would contain:

`
...
  "Favorite dish": "Pizza"
...
`

**Comment by Byenkya** [comment]
Hello thanks for the feed back, but that page has the following endpoints
1. RestAPI for Actor Details
2. RestAPI for Country Property Actions
3. REST API for Default patient template Details
4. REST API for managing patient templates.
5. REST API for managing person statuses
6. REST API for managing scheduled messaging services
7. REST API for managing template.
8. REST API for message trigger actions

So among these where does /patientRegistration endpoint fall cause I wasn't able to see it there.

**Comment by pwargulak** [comment]
Hi @Byenkya 
In Connect for Life, and in OpenMRS in general, we don't have special REST APIs just for 3rd party apps like mobile apps.
You would use the same REST as our FE uses - if it uses REST.

For finding out what request to make, I suggest the old and trusted browser's network tab; visiting the page, doing actions via UI and inspecting the request made by our FE.

As for the patient registration.
There is OpenMRS standard endpoint documented here: https://rest.openmrs.org/#create-a-patient 

In Connect for Life, the Front-end uses custom one:
POST http://{{host}}:{{port}}/openmrs/ws/cfl/patientRegistration
_Headers_:
Cookie: JSESSIONID=...
_Body_:
{
    "LocationAttribute": "8d6c993e-c2cc-11de-8d13-0010c6dffd0f",
    "Nationality": "Belgium",
    "Telephone Number": "63123123123",
    "Vaccination program": "Vacc1",
    "address1": "Address1",
    "address2": "Address2",
    "birthdate": "2022-07-04",
    "birthdateEstimated": false,
    "cityVillage": "City",
    "country": "Country",
    "familyName": "FamilyName",
    "gender": "M",
    "givenName": "HelloWorld",
    "middleName": "MiddleName",
    "personLanguage": "English",
    "postalCode": "PostalCode",
    "stateProvince": "State"
}

You'll get the JSESSIONID cookie when you login, the endpoint doesn't support Basic authorization.

**Comment by Byenkya** [comment]
Is there an API endpoint where I can post patient symptoms in connect for life Distribution based on patient ID and also another API endpoint to get patient symptoms to based on the ID

**Comment by Byenkya** [comment]
Sorry to bother you again but could you help me with the link to all the custom API end points for Connect for life like this one ->http://{{host}}:{port}}/openmrs/ws/cfl/patientRegistration I believe it will solve my issue. I need to where they are located. Thanks

**Comment by hkaluuma** [comment]
> Sorry to bother you again but could you help me with the link to all the custom API end points for Connect for life like this one ->http://{{host}}:{port}}/openmrs/ws/cfl/patientRegistration I believe it will solve my issue. I need to where they are located. Thanks

I am also at the same point and would like directions on where I can find the custom APIs similar to the one which has been shared "http://192.168.1.101:8080/openmrs/ws/cfl/patientRegistration" the shared endpoint works very well.

**Comment by pwargulak** [comment]
Hi @hkaluuma
I'll try to make the complete list, but for now you could inspect the "... REST API" links in the Advanced Administration page.

**Comment by Byenkya** [comment]
@pwargulak 
I have tried to inspect the REST API's in the Advanced Administration page. But I can't seem to find the custom Connect for Life endpoints there like this one -> POST http://{{host}}:{{port}}/openmrs/ws/cfl/patientRegistration.

**Comment by Byenkya** [comment]
@pwargulak 
Is there any API endpoint in Connect For Life I can use to retrieve PatientFlags. Have tried the Advanced Administration Page but all in vain. Any assistance please.

**Comment by pwargulak** [comment]
Hi @Byenkya 
the OpenMRS framework itself is missing the REST interface for Patient Flags module, they had an idea to add it but no one did:https://issues.openmrs.org/browse/FLAG-24

In Connect For Life we didn't need the REST, so we didn't add it too.

**Comment by Byenkya** [comment]
@pwargulak 
The best contact time API endpoint (i.e **http://localhost:8080/openmrs/ws/messages/actor/contact-time**) uses personID to set the contact time for a particular patient but for some reason most Openmrs endpoints do not return this personID. They instead return the person uuid yet that endpoint needs the personID. Some assistance please.

**Comment by pwargulak** [comment]
Hi @Byenkya 
we are aware of this inconsistency.
The workaround may sound a little hacky, but here is an endpoint which returns personId (in addition to patient's communication consent status):
/openmrs/ws/messages/person-statuses/{uuidOrPersonId}

{
   "title":"translation key for consent status",
   "value":"consent value",
   "style":"CSS styles to use when showing title",
   "reason":"nullable, reason for the status",
   **"personId":int,**
   "personUuid":"uuid"
}

**Comment by pgesek** [comment]
We have moved this repository to: https://github.com/johnsonandjohnson/openmrs-distro-cfl

If the issue still persists, please create it again in that repository. Sorry for the inconvenience.

Regards,
Paweł
